### PR TITLE
Added functionality to create VBA code

### PR DESCRIPTION
**Pull request by monoxgas**

### CODE REVIEW

**Comment by tyranid** [comment]
Just a few minor changes if possible. Could you add a check for VBA mode if someone also specified a moniker output which prints an error. It might confuse people into thinking they could generate a scriptlet with VBS and complain why it doesn't run.

And could you add an AUTHORS text file to the root of the project and throw my name and yours in there (I didn't really expect anyone to contribute tbh ;-)

**Comment by monoxgas** [comment]
Good call on that, corrections made.

I figured contribution wasn't expected either, but I hate project fragmentation. Thought I would go straight to the source :)

**Review by tyranid — CHANGES_REQUESTED** [review]
Few nits. Could you use the WriteError method to print the error for mismatched options and fix the typo of scrip(t)let in the string. Also GitHub doesn't like that there's no trailing new line in the AUTHORS file.

**Comment by monoxgas** [comment]
Done, done, and done.

**Review by tyranid — APPROVED** [review]
Looks good. Thanks very much for your work.

**Pull request merged**
